# 1.3 异步编程与“回调地狱”

```js
const fs = require('fs')

fs.readFile("./test1.txt", "utf-8", function(err,content1){
	if (err) {
		console.log(err)
	} else {
		fs.readFile(content1, "utf-8", function(err,content2){
			if (err) {
				console.log(err);
			} else {
				fs.readFile(content2, "utf-8", function(err,content3){
					if (err) {
						console.log(err);
					} else {
						console.log(content3)
					}
				});
			}
		});
	}
});

console.log('主线程')


try {
	console.log(content3)
} catch(e) {
	console.log("还没有获取到content3！");
}
```

读取的每一个 .txt 文件中的内容是要读取的下一个文件的路径地址，最后一个txt文件（test3.txt）中的内容是“callback hell is not finished......”

打印结果：

```
主线程
还没有获取到content3！
callback hell is not finished......
```

可以理解为Node代码一根筋的往下想尽快结束所谓的主线程，所以遇到设计异步的就自动忽略并跳过为了往下执行，所以出现了第一句非异步的打印操作，打印“主线程”，再往下执行遇到需要打印 content3 这个变量的时候，主线程就“懵”了，因为命名空间内并没有获取到任何 content3 的数据，甚至在主线程命名空间内都没有定义这个变量，如果不用 try-catch 那么应该会报 “content3 is not defined”的错误。

此外，callback hell 一览无余，一味地因为依赖而采用嵌套回调函数的方式，哪怕是上述代码那么简单的一个原子性的操作都会被这种**“横向发展”**的代码和无休止的大括号嵌套让业务逻辑代码丧失掉可维护性和可读性。

为了避免这种回调地狱，解决问题的方案和第三方模块就开始层出不穷百花齐放了。